### ISSUE TITLE
Minimum cash required

### ISSUE THREAD

**Issue by am071092** [puddingspudding/just-the-dip#4]
I've been playing with the bot but i keep running out of cash. How do you tweek the minimum buy order?

**Comment by puddingspudding** [comment]
The minimum buy order size used to be 20 EUR/USD. Seems they changed it to 10. https://www.bitstamp.net/fee-schedule/#min-trade-amount. The minimum cash is basically calculated like this
> min order * 100 / stepsPct * (100/totalPct)²

with my current settings

> -DtotalPct=100 -DstepsPct=4 -DsellPct=4 -Dpair=XLMEUR -DmaxFiat=1000000

 it would be 250 but I recommend using twice as much

**Comment by am071092** [comment]
okay. Can you share what strategy the code is using? Also, is the program meant to be run constantly?

**Comment by puddingspudding** [comment]
It is meant to run using crontab every few minutes. Between 1 and 5 minutes is fine.

The strategy:
Step 1: Delete all open buy orders if the difference between the highest buy order and current price is bigger than _stepsPct_. If not do nothing
Step 2: Create limit orders in _stepsPct_ increments below current price until _totalPct_ is reached, no cash left  or _maxFiat_ reached (buy the dip). The orders created will have a limit sell order _sellPct_ higher than the buy price attached to it and will be placed if the buy order is executed.
